services:
  - type: web
    name: bookstore-app
    env: docker
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar /opt/app/app.jar --server.port=$PORT"
    envVars:
      - key: PORT
        value: 8080
